Updated install instructions
dracula/windows-terminal pull request #9
Opened 2020-10-19 11:37 UTC by guigsc

2020-12-10 00:41 UTC, thismat reviewed
I appreciate the update. I'm not really a fan of the error highlighting that happens when using comments in JSON. I had that before as well and did not like the look and feel of it. 

I'm open to suggestions on changes. Maybe using it without syntax highlighting is the way to go?

2021-08-17 23:44 UTC, NatoBoram requested changes
This should remove the errors.

2021-08-17 23:44 UTC, NatoBoram commented on INSTALL.md
> +```json
```suggestion
```jsonc
```

2021-08-17 23:44 UTC, NatoBoram commented on INSTALL.md
> +```json
```suggestion
```jsonc
```

2021-08-18 00:02 UTC, thismat commented
@NatoBoram Very nice! Thanks!

2021-08-18 00:03 UTC, merged